# Generated by Django 4.0.4 on 2022-06-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ken_portfolio', '0002_destination_offer_destination_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='img',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
